### ISSUE TITLE
Game crashed during startup

### ISSUE THREAD

**Issue by drenough** [TinyModularThings/IC2Classic#370] opened 2019-09-28 10:06 UTC
I'm using version: IC2Classic 1.12-1.5.4.4

It started crashing when I use via CraftTweaker zen script for change every iron ingots to iron plates.

Crash log here: https://pastebin.com/WRsjubwy

**Comment by Speiger** [comment] 2019-09-28 16:18
the issue is that logs do not have a output for their crafting recipe. 
This is a ic2c issue that it returns the wrong data and causes a crash but its triggered by registering a log that does not have a recipe to planks. (Using the recipe list for the saw mill to find out which log has which plank as a output and duplicate the recipe)

**Comment by Speiger** [comment] 2019-09-28 16:18
will be fixed in the next version

**Comment by Speiger** [comment] 2019-09-30 17:31
fixed

**Closed** 2019-09-30 19:46 UTC
