### ISSUE TITLE
Cannot remove Transformer Upgrade when "EnableKeysInGuis" Config option set to "False"

### ISSUE THREAD

**Issue by AtomicWaffle14** [TinyModularThings/IC2Classic#284] opened 2018-11-20 20:43 UTC
I can't remove the Transformer upgrade using any combination of clicking and pressing the Alt key like it says in the tooltip. This a bug?

![2018-11-20_14 07 09](https://user-images.githubusercontent.com/39530149/48801698-0a52ed80-ecdb-11e8-987a-44bfd77fff4e.png)

**Comment by Speiger** [comment] 2018-11-21 01:09
No not a bug. I just tried it. It works fine. My guess is: "Keybinding Conflicts"

**Comment by Speiger** [comment] 2018-11-22 07:01
Yeah. On the other hand you can change it in game realitivly quickly.
Like Hit Esc => Go to ModSettings => Select IC2C => Select Config => Select Client => Change setting => Close gui.

Ok just to throw this information out. What if you have a machine set into a HighVoltage line. I have to make sure that you can not i mean can not pull out the upgrade on accident. Because if you do that. The machine will blow up. Do you want to have a machine blow up because of a accidental picking up of a upgrade?
So i have to use keybindings some how. Shift is a bad idea.

And here is the issue: MC has no i mean no Key Synchorinzation on its own. So i can not even check if a key is pressed because its client only. This feature is unique to the mod.

So tell me a good way to make this happen that isnt worse then this!

What i suggest you is make your keybindings settings so you dont conflict with jei.

**Comment by AtomicWaffle14** [comment] 2018-11-22 15:57
Alright, so firstly, changing my keybindings so they don't come flict with JEI is very difficult, because in order to search by item name I have to type letters. This means potentially any letter key may be pressed, thus restricting my ic2 controls to a very small set of rather inconvenient to press keys, like punctuation, function keys, and the numpad. 

Second, I have a couple of ideas that may make the problem less difficult:

1. If the EnableKeysInGUIs option is set to true, do not display the message in the UIs saying that you can press it to remove the upgrade. Instead say that you must pick up the machine. Upon doing so, make any transformer/locked upgrades pop out.

2. The Alt key does nothing on it's own, unless pressed with another key, right? Would it be possible then to disable all keys *except* the Alt key when setting EnableKeysInGuis to false? This would definitely require some testing but theoretically it should work, unless the keybindings are all linked under some unchangeable behavior.

3. Add a separate keybinding that does not follow the EnableKeysInGuis rule and use that to remove locked upgrades. Also may be problematic based on how controls are linked

4. Add a small button in the machine interface that you must click in order to unlock locked upgrades. Add a precaution where it has a timer, twice click, or something to prevent accidents.

5. Lock transformer upgrades if and only if a cable, transformer upgrade, or power storage block is adjacent to the machine. This would require checking neighboring blocks. Is a machine capable of doing that?

I hope at least some of these ideas are good/doable. It just doesn't make sense to me in game that when I'm in a machine interface and I press the space bar while wearing a jetpack, my character will fly away from the machine I'm looking at. 

Thanks for your hard work and consideration.

**Comment by AtomicWaffle14** [comment] 2018-11-22 17:17
Okay, thanks for the info. In that case, I have one final suggestion that may be better than all the rest.

My final suggestion is that if keys are enabled in GUIs, all tools/armor actions will work only if a GUI is **not** open. This way, you don't have to change how the keybindings are handled, just how the tool/armor actions are handled. It would just require one additional condition (a GUI not being open) being added to their actions along with the key press, right? I know it's probably a little more than that but I feel like this solution makes a lot of sense.

This way, only the tools/armor would be prevented from working when a GUI is opened, and not the other key functionalities. Unless being able to fly or toggle night vision when a GUI is open is really really important, I think this would be a good fix.

**Comment by AtomicWaffle14** [comment] 2018-11-23 04:13
> 2\. Thats not wrong: Memory Stick (delete data), Wrench (alternative Rotation), MiningDrill (Use Scanner), Obsucrator (All side affect instead of 1 side), Quarry Scanner (Radius change), Upgrades (Setting owner), ItemLimiterUpgrade (settings). To give that point. The key has a lot of uses on its own. Some are even in guis itself.

This is the big one. Nowhere have I been able to see the Alt key do anything outside of a gui without the need for a mouse button to be clicked. I have tested this with many different items (with KeysEnabledInGuis set to *true*). In addition, none of these items will activate when pressing the Alt key and mouse button when a gui is open, probably due to the way click events are treated. In conclusion, why is it necessary to disable the Alt key with KeysEnabledInGuis set to false in the first place? 

I have found a very simple solution that only requires changing only a single line of code. 
In *ic2\core\platform\player\KeyboardClient.java*, there is a function called **sendKeyUpdate( )**, which  controls what keys are being sent to the server. The **currentKeyState** integer is being built from a series of bits that correspond to each keypress, with the Alt key being the first (conveniently). When the *guiDissabled* setting is true, and a gui is open (mc.field_71462_r != null), the currentKeyState will be forced to 0, essentially nullifying all of the keys. It will also do this when the chat is opened **(mc.field_71462_r instanceof net.minecraft.client.gui.GuiChat))**. 

![image](https://user-images.githubusercontent.com/39530149/48928278-5bb1d700-eeab-11e8-9626-b4dff1435dc8.png)

However, because the Alt key does not need to be forced to 0, we can allow it through.

The if statement must be broken into two separate ifs, one for each condition. In the first (where guiDissabled and gui being open), have the currentKeyState be set to itself, logically ANDed with a 1. This will allow the first bit (Alt key state) through, while nullifying all other key states. Then, for the second if (where chat is open), have it set currentKeyState to 0. 

Here is how I would change the code:

![image](https://user-images.githubusercontent.com/39530149/48928304-9ae02800-eeab-11e8-9e57-6da72d8ba4ea.png)

Does this make sense?

**Comment by Speiger** [comment] 2018-11-23 11:01
You are aware that this is a intendet feature how it is programmed?
Removing part of this feature (what you are suggesting) is basically suggesting that i could just remove the entire config setting because you can never be sure if a addon or ic2c is going to use other things like that inside of a gui correct? 

And since i am tired of that disscussion, i am going to close this and tell you. Live with it, or just dont use upgrades that have a transformer changing effect.
Or just break the machine with wrenches instead of removing transformer upgrades.

Anyway this is over now. Bye

**Closed by Speiger** 2018-11-23 11:01 UTC

**Comment by AtomicWaffle14** [comment] 2018-11-23 14:36
You could have just said "I don't want to change my code" at the beginning and I wouldn't have wanted a few hours of my time trying to find a solution for you. I'm sorry I like your mod and I want to improve it.

**Comment by Speiger** [comment] 2018-11-23 14:54
has nothing todo with "I dont want to change my code", its: I dont want to change this feature.

**Comment by AtomicWaffle14** [comment] 2018-11-23 14:55
Gotcha. I'll stop bugging you then. :)
