### ISSUE TITLE
Monsters, animals, or pets do not take into account armor or item attributes

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#686] opened 2023-03-13 03:11 UTC
I threw away the nano armor and the activated nano saber of the zombie, and decided to kill him, the nano armor on him does not waste energy and does not give him protection, and the nano saber does not give him damage. I also use the Neapolitan mod where you can tame monkeys and create your own army, when I give them an activated nano saber, its attack attributes are not taken into account.

**Comment by MrJorman** [comment] 2023-03-13 03:12
I want all the attributes and functionality of armor and weapons to be taken into account on animals or monsters.

**Comment by CrossVas** [comment] 2023-03-13 03:15
Duplicate of #664. What is wrong with you?
This is intentional.

**Comment by MrJorman** [comment] 2023-03-13 03:15
Sorry, I thought my ticket was closed and forgotten.

**Comment by MrJorman** [comment] 2023-03-13 03:16
And the mistake is unpleasant (

**Comment by CrossVas** [comment] 2023-03-13 03:17
Please, use discord for further questions, do not spam issues on github.

**Closed** 2023-03-13 09:28 UTC
