### ISSUE TITLE
Geothermal generator randomly stop working

### ISSUE THREAD

**Issue by DBotThePony** [TinyModularThings/IC2Classic#411] opened 2020-05-26 09:23 UTC
And then they never activate ever again

IC2 Classic version: 1.12-1.5.4.5
Forge version: 14.23.5.2854
![2020-05-26_16 17 06](https://user-images.githubusercontent.com/6339511/82883291-6d76ad80-9f6c-11ea-9259-24732a5422bb.png)
![2020-05-26_16 17 07](https://user-images.githubusercontent.com/6339511/82883299-6ea7da80-9f6c-11ea-853f-ece4f30a71ce.png)
![2020-05-26_16 17 10](https://user-images.githubusercontent.com/6339511/82883301-6f407100-9f6c-11ea-864d-054de866b2d2.png)
![2020-05-26_16 17 11](https://user-images.githubusercontent.com/6339511/82883304-710a3480-9f6c-11ea-9abe-5efd090594e6.png)
![2020-05-26_16 17 14](https://user-images.githubusercontent.com/6339511/82883312-72d3f800-9f6c-11ea-84f0-a0eca555917e.png)
![2020-05-26_16 17 15](https://user-images.githubusercontent.com/6339511/82883316-74052500-9f6c-11ea-91c2-093f8349c26e.png)

**Comment by Speiger** [comment] 2020-05-26 09:26
Eh this is not something random actually.
The geothermal generator only outputs what it has in charge left but only produces power if the buffer is empty.
Loss >= storedBuffer = Lookdown.
Simple Fix: Use better cables.

**Comment by DBotThePony** [comment] 2020-05-26 09:29
i should use superconductor then? because there is no way i can extract 1 EU from buffer using any of cables

**Comment by Speiger** [comment] 2020-05-26 09:31
Loss is rounded down in IC2C. In other words as long the total loss is not big enough to reach a natural number then you are fine.

**Comment by DBotThePony** [comment] 2020-05-26 09:35
I know what is `math.floor` (rounding down) is. Issue here is that it is not obvious why it stop working and why it can't go ahead and generate power if total loss is lesser than it's internal buffer. Because the only way to workaround this loss is to either install glass fibre cables (which are HV, and it might be an issue since for many players) or using superconductor from GregTech (which is also HV)

**Comment by Speiger** [comment] 2020-05-26 09:41
how about introducing transformers into the equasion.
Note that this bug existed for the entirety of IC2?

Anyways the enet is right now not capabable of catching such situations. And growing the buffer isnt fixing the problem. And yes we had this bug happen during testing but we decided it is more of a user error then a "bug"

**Comment by DBotThePony** [comment] 2020-05-26 09:45
Fine. But you should somehow implement warning somewhere about this situation to prevent severe confusion of end users in such situations.

**Comment by Speiger** [comment] 2020-05-26 09:49
you are only the second person after around how many years i develop this mod which caused this bug, and lets not include IC2 before my ports.

**Comment by DBotThePony** [comment] 2020-05-26 10:20
Saying that "this design fault preserved from older IC2 versions" is not an valid answer.

**Comment by Speiger** [comment] 2020-05-26 22:09
The issue is: How do I detect that it is because of energy loss?
The energynet is right now not capable of detecting such a thing and implementing such a feature isnt as easy with java 7 (default interfaces do not exists there)

The crude solution would be: if the power is <20 and it couldnt didnt send energy the last tick then just refill the buffer. But honestly: NO you don't want that. That makes the geothermal generator void because then you can use a normal generator instead.

**Comment by DBotThePony** [comment] 2020-05-27 01:27
Java 7?

**Comment by Speiger** [comment] 2020-05-27 01:43
my forge enviorment is set to java7 in 1.12 and that is something i will not change

**Comment by Speiger** [comment] 2020-05-27 05:13
I leave this one open.
I am still debating if this should be addressed or not. It requires me to actually does new API additions to make possible and I am personally not happy about that thought.

**Comment by Speiger** [comment] 2020-06-14 07:04
Closing. Decided that i am not implementing this.

**Closed by Speiger** 2020-06-14 07:04 UTC
