### ISSUE TITLE
[Bug] Nanosuit Armor

### ISSUE THREAD

**Issue by draldan** [TinyModularThings/IC2Classic#104] opened 2015-08-15 10:14 UTC
The release is close to bugfree, although the one I found is kinda nasty. The nanosuit armor, or at least the boots, don't protect against damage. I hope it's not too bad to fix :)

**Comment by Speiger** [comment] 2015-08-15 15:52
Well it depends on the Damage. If it is not unblockable it should prevent a bit of damage,
you should know that the shoes absorb 50% less then the Helmet.. (It is the weakest part)

**Comment by draldan** [comment] 2015-08-16 09:16
But back in the day you were completely immune to fall damage if you wore the whole suit, in this version that's not the case :/

**Comment by Carbon-Ghost** [comment] 2015-08-16 16:42
Nope, only boots ;P the fact that the suit completely absorbed all damage was considered as a bug, it should only behave like an electric diamond armor with 90 % absorption if full armor is worn which is 10% better than diamond ( we also fixed the bug where the armor didn't gave a full armor bar although it was better than diamond... ) , but the Q suit like you said should try to lower all types of damage ;) Worst case feather falling III might be your best friend ;) But we should keep this open for discussion for possible changes though..

**Comment by Speiger** [comment] 2015-08-16 19:59
@draldan nanosuit boots only absorb 100% damage when you have less the 4 hearts damage...
If it 4 hearts or more it is only 87,5% damage absorbtion...

**Comment by Speiger** [comment] 2015-09-07 09:14
Not a bug so closing. If it is a bug and i missreaded then just tell. @draldan

**Closed by Speiger** 2015-09-07 09:14 UTC
