### ISSUE TITLE
Wiki Book 

### ISSUE THREAD

**Issue by GenzongGaming** [TinyModularThings/IC2Classic#843] opened 2023-07-18 21:27 UTC
Please add a config option to disable the give players book on join. 
Meduris on your discord mentioned that the issue of forced book on 1st join had came up prior. 
While I agree it's best to have it set to true by default, for pack devs it can be pretty annoying as I have Eccentric Tome which means that the book is given to players and is in the tome itself. While this can be disabled by Kube/Tweak magic it's a bit annoying.

Hence add a new config option like you see in other mods for people to freely toggle as they see fit and have it set to true by default.

**Comment by Speiger** [comment] 2023-07-18 22:43
@GenzongGaming I am still on the fence with this one.
Where I don't want to provide an easy way to disable the wiki, because without it anyone new basically gets stuck with the mod.

On the other hand I kinda want to provide a way to make this easier for pack devs.

I am not saying "No", but atm i am stuck with what i want :)

**Comment by GitJhopa** [comment] 2023-07-18 22:56
Just add a function in ic2c.cfg

#Whether all players should get an IC2 Wiki Book when joining the world for the first time.
giveBookOnStartup = true

**Comment by SigmaFlame** [comment] 2023-07-26 00:04
Do you know a mod that allow, in 1.18, to delete these books given to new players?

**Comment by Speiger** [comment] 2023-07-26 00:17
@SigmaFlame the book is atm not auto removable via configs because it is a HUGE mod where you can easily fall into: What do i do now? or "How can do this better" and there is essential tips in there you don't really think about.
And ensuring that people don't turn of wiki books by default is essential in this case.
Does it piss people of? Maybe? Can they throw it away? Yes
Do i even write that it will be the least used item in the mod? Yes too.

Honestly if i get a ton of books i simply throw them away until i need them.
But at least i know its there.
With a over 500 page wiki be happy that it exists at all because it almost didn't make it at all and then you have to fight with: is this 1.12 or 1.19.

In a later patch i will include inconvenient ways to disable it because pack devs need it but atm the mod is new enough to most people that I am enforcing it so knowledge can start to spread.

**Comment by SigmaFlame** [comment] 2023-07-27 03:26
I really do not understand why you do not want that players to be able to disable your wiki book.
I understand that the wiki book is essential, but all wiki books from all other mods are easily craft-able.
I mean that these wiki books should always be able to be crafted in the early game stage.

Let me explain my point:

1. The wiki book is enabled by default, so the majority of players will still get it.
2. The players who want it disabled have to launch the game first, then close it, then go to the config in order to turn it off.
3. A warning can be added inside the config file to warn the user that the wiki book is essential.
4. For those who still want the wiki book disabled, they have still the ability to craft it in-game later, in a survival way.

A most complicated way to disable the book, ideal for servers, harder for players and greatly inconvenient for mod packs, is to make this precise configuration only available through the server's configuration of Forge, that is located inside the save folder.

The player have to create a temporary world first, then close the game, go to the config of that world, edit the configuration file, copy it inside the "defaultconfigs" folder, then re-launch the game and create their new permanent world.

Some mod packs and servers process differently to get these books:

1. Like I said before, some servers prefer to let their players craft these books by themself, in a survival way.
2. Some servers have a library built near of the spawn where all these book are available, in exchange of in-game money.
3. Few mod packs make these books only findable as treasure: dungeons, fishing, and so on, in a very immersive way.

The third point is really immersive, since it is normal that you do not know these technologies, and you have to find this ancient knowledge first. You have to keep the book preciously inside a chest in order to keep it safe, of course far away of your machines in order to prevent the book to be destroyed if one of your machine explode.

That's my point.

PS:

I really appreciate the configuration option to decide if the game would be paused or not while reading the wiki book.
I really hate when wiki books from mods pause the game, and making it possible to disable this behavior is greatly appreciated.

**Comment by Speiger** [comment] 2023-07-27 12:02
> I really do not understand why you do not want that players to be able to disable your wiki book.
I understand that the wiki book is essential, but all wiki books from all other mods are easily craft-able.
I mean that these wiki books should always be able to be crafted in the early game stage.

Its fairly easily explained. A ton of people by default when they see a config option to turn of the spawn of a wiki book do that by default. LIKE ACTUALLY BY DEFAULT.
So anyone who is doing that is out. And i expect that to be a lot since modpacks are not free from that either.
Proof? This request specifically.
Then we have the thing that this mod is not simple in the first place and it is a niche mod too.
In other words there isn't much "online information" out there, (anyone asking NO you know who you are).
And the information out there is for different game versions which has its own set of problems. (think Thaumcraft)

That + the compound that people do not actually read it all the time and we have a scenario where i do have to push it into people faces. if they like it or not.
That is also the reason why i say: AT THE MOMENT I AM NOT ADDING THAT.
I want information to build up a bit before i relax things.

And its not like there is no way to disable it, for modpacks you are just kinda forced to throw in a Script to disable that.
Is it a good way? No. Does it fulfill a purpose? Yes. 

>Let me explain my point:
>- 1: The wiki book is enabled by default, so the majority of players will still get it.
>- 2: The players who want it disabled have to launch the game first, then close it, then go to the config in order to turn it off.
>- 3: A warning can be added inside the config file to warn the user that the wiki book is essential.
>- 4: For those who still want the wiki book disabled, they have still the ability to craft it in-game later, in a survival way.

- 1: Already explained. People who see the name: "turn of wiki" turn it off instantly. That is a argument for not having it in.
- 2: Not really a counter argument since (1) isn't invalidate with that since ALL MODS require it and with that its not an extra step.
- 3: I know enough people who don't even read comments and just skip it. I can say that i include myself to that every now  and then too. Doesn't invalidate (1). You can write in HUGE RED LETTERS: IF YOU TURN THIS OFF YOU LOSE ANY RIGHT TO SUBMIT BUGREPORTS, and people will ignore it.
- 4: Lets hope they are not to noobish and the wiki even warns you that it will be hell and back to get to that point because you have to progress through the early game blind to get it back. Yes that is a intentional punishment. And no that will not change.

> A most complicated way to disable the book, ideal for servers, harder for players and greatly inconvenient for mod packs, is to make this precise configuration only available through the server's configuration of Forge, that is located inside the save folder.

Not like people have to write it multiple times for each version. Its literally just once. Making it hard for the normal player so they HAVE TO HAVE IT is the point you are not getting at.

>Some mod packs and servers process differently to get these books:
>- 1: Like I said before, some servers prefer to let their players craft these books by themself, in a survival way.
>- 2: Some servers have a library built near of the spawn where all these book are available, in exchange of in-game money.
>- 3: Few mod packs make these books only findable as treasure: dungeons, fishing, and so on, in a very immersive way.

- 1, 2, 3: You still can disable it, there is still a way to do it, its just really inkonvenient.


> That's my point.

And that is fine, but in the end you have only a outside image of what is happening.
I hope this attempt of showing the inside of whats going on makes you at least more accepting of this information.

> I really appreciate the configuration option to decide if the game would be paused or not while reading the wiki book.
I really hate when wiki books from mods pause the game, and making it possible to disable this behavior is greatly appreciated.

It was the reverse actually.
It wasn't pausing the game in the first place. Until someone was managed to be killed by a creeper with it.
Then the config was added to give a option.

Anyways @SigmaFlame you are not helping @GenzongGaming request.
You are atm reinforcing my view that i should keep it the way it is.

just FYI.

**Comment by GenzongGaming** [comment] 2023-08-01 20:16
Yeeeeeeeeesh. What did I come back too?          '-' 

I just asked for a config option so I could be lazy and not have to write up a KubeJS or CraftTweaker script to disable spawning with Wikibook and to make the mod more modpack friendly. @SigmaFlame if you don't like the way the mod is done go make your own IC2 mod with a config with the wiki being able to be disabled. It's annoying and IMO not the best of ideas but I aint over here being an arsehat about it '-'

**Comment by Speiger** [comment] 2023-08-21 18:18
Small update.
Welp here is the reason why...
![image](https://github.com/TinyModularThings/IC2Classic/assets/2556269/005c31e7-accd-4b96-b752-5682abd9a63c)

**Comment by SigmaFlame** [comment] 2023-08-21 19:39
An online wiki is available here : https://github.com/TinyModularThings/IC2Classic/wiki

And I suggest you to make your ingame wiki accessible throught a keybind instead of an item that you can lost.
Some developers also managed to add buttons on Just Enough Items to access their wiki, but I don't know how to do that.

But please, wait the next minecraft version before removing an item from your mod, the worlds don't really like that.

**Comment by Speiger** [comment] 2023-08-21 20:00
@SigmaFlame that wiki is 1.12, while not entirely different, there is key changes that make it inaccurate xD

And about the keybind, that may be with the next MAJOR version of IC2C (major => new mc version)

**Comment by SigmaFlame** [comment] 2023-08-21 20:02
1.20.2 ?
The wiki book as item will be removed ?
So the issue is solved then.

**Comment by Speiger** [comment] 2023-08-21 20:31
@SigmaFlame ¯\_(ツ)_/¯

**Comment by Speiger** [comment] 2023-09-06 14:27
@GenzongGaming this update contains a tag.
"ic2:items/spawn_wiki" if the wiki item itself is in the tag it will not attempt to spawn.
This makes it ANNOYING, but also not rely on mods. and on top of that it can be dynamically enabled/disabled.

Also really easily implementable without making it to easy to disable.

**Closed** 2023-09-08 21:38 UTC
Labels: Fixed

**Comment by SigmaFlame** [comment] 2023-09-09 13:21
I saw you added a way to disable the wiki book, thanks a lot. ^_^

**Comment by Speiger** [comment] 2023-09-09 16:07
@SigmaFlame until you realize that this effectively the exact same as it was before, you simply just don't rely on a mod anymore.
