### ISSUE TITLE
The wiki book doesn't show a full description of the mechanism

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#680] opened 2023-03-11 23:45 UTC
The wiki book doesn't show a full description of the mechanism, I can't figure out what it does.
![image](https://user-images.githubusercontent.com/55187962/224516564-2d109763-5842-4f04-b562-b6de25ff2ab4.png)

**Comment by Meduris** [comment] 2023-03-11 23:51
@cubicbyte could you potentially check this out?

I am not sure if this is an issue you ran into when you did the translations

**Comment by cubicbyte** [comment] 2023-03-12 05:23
That's because I translated everything except the wiki, and this is its old translation, and it has a lot of that stuff in it.

Sometime in the next few months I'll be playing with ic2c again, and Maybe I'll finish the wiki sometime :)

**Comment by Speiger** [comment] 2023-03-12 07:01
yeah the wiki has a few conditions where you have to translate for it while keeping the original size in mind.
Which is a hard ask for any translators.
We have 2 options.
1: Ignore it.
2: Delete all the wiki translations except 2 entries. (the translation credits)
Then you have to deal with the english version.

But this is technically not a bug in my eyes. so closing.

**Closed by Speiger** 2023-03-12 07:01 UTC

**Comment by MrJorman** [comment] 2023-03-12 11:07
It turns out I need to translate to the end or what? Players complain that nothing is clear

**Comment by cubicbyte** [comment] 2023-03-12 11:15
Unfortunately, the best solution right now is to use the English version of the wiki - on the [website](https://github.com/TinyModularThings/IC2Classic/wiki) (recommended) or with the English language in Minecraft

**Comment by Speiger** [comment] 2023-03-12 12:14
@cubicbyte that website you linked is 1.12.2 Not 1.19.2
Do you suggest we delete the auto translation?

@MrJorman well we can just remove the translation then people can deal with the english version.
Or you can finish it yourself. 
But its a TON of things to translate.
if you want to do the work thats fine.

**Comment by MrJorman** [comment] 2023-03-12 12:15
I'll translate it myself)

**Comment by Speiger** [comment] 2023-03-12 12:25
@MrJorman here is the file.
https://github.com/TinyModularThings/IC2Classic/blob/1.19.x/src/main/resources/assets/ic2/lang/wiki_ru_ru.json

If you want to translate it please do a pullrequest.

**Comment by Speiger** [comment] 2023-03-12 12:26
The cutoff areas are most likely "wiki.ic2.preview." entries.

**Comment by MrJorman** [comment] 2023-03-12 12:26
ok
