### ISSUE TITLE
Don't get back cells from the canning machine?

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#235] opened 2017-08-30 17:51 UTC
I assume this was intentional, though I was wondering why? Is it a balance decision? Was it an oversight? Are you just imitating the original IC2 behavoir?

**Comment by laz2727** [comment] 2017-08-30 17:51
Cells are supposed to be disposable.

**Comment by abculatter2** [comment] 2017-08-30 18:06
Would it be possible to get a renewable alternative for fuel cells, possibly made of plastic made from smelting rubber?  Or just crafting it out of rubber? I wouldn't mind if tin cells are definitely better, though it seems like the vast majority of people (myself included) would view bio- and coal-fuel as useless if the only way to burn it consumes tin.

**Comment by Speiger** [comment] 2017-08-30 21:19
@abculatter2 well biofuel or coalfuel arent a liquid in IC2Classic...
Thats the issue.
On the other hand its not dropping the cells because how do you drop that kind of item?

**Comment by abculatter2** [comment] 2017-08-31 04:30
Can't you make them liquids? It would make sense for them to be so...
Also, why not add a slot to the canning machine's GUI as a place to put empty cells? Or add them to the hidden secondary slot that seems to exist for catching excess items in machines, and outputs when the output slot is emptied? (not sure if this is actually a thing, but I noticed it happen with an extractor when it got full of rubber) I don't really understand what you mean by 'how do you do that' in this case...

Also, personally, I actually like the idea of disposable metal containers, conceptually, but the way it's implemented here feels too expensive. Another thing that might help is to decrease the cost of cells, maybe down to a nugget per cell? I feel like that would be a small enough amount of metal used that I would be willing to do it without a renewable tin supply, especially with the new additive system (which I think is a really good addition, by the way)

**Comment by Speiger** [comment] 2017-08-31 11:09
Well the issue is there machines would habe to have a tank to process things. A bottler/unbottler would have to be implemented and other things. On top of that using these fuels would make the boiler more useless since these things are not really usefull when you have easier methods.

The secondary output slot could be a solution I think about that.

About the hidden inventory yes that's a thing for some machines. A canner on the other hand has nothing in that regard. Because it uses not the basic recipe system like all the other machines.

And I have implemented that hidden inventory to allow mods to add multiple outputs to ic2 machines. Its a bigger more flexible system then ever before. Chance base things and other things people could implement. 

About tin not being not renewable is a 100% lie...
You have 3 methods to generate resources in IC2:
- 1: UU-Matter. A bit expensive
- 2: Scrapboxes. Havyly around RNG.
- 3: Crops, a steady and constant supply crop.

So yeah generating tin copper, silver, gold, iron is possible through these things and crops have their output dramatically increased. 

And there is even a difficulty mode where you can make it harder or easier to grow crops. (I do not suggest very easy since that makes them actually harder at a certain point)

**Comment by abculatter2** [comment] 2017-08-31 17:01
I did not say that tin is non-renewable, I was saying before you have renewable tin actually set up, you don't tend to want to use your tin for fuel. Since this tends to be fairly early game, this tends to be especially true, since the player hasn't accumulated the masses of resources necessary to build stacks of renewable generators. This would be the best place for fuel-based generators to shine.

**Comment by Speiger** [comment] 2017-08-31 18:23
@abculatter2 using fuel cells with that would be inefficient in the first place. You use usually only 2-3 cells per fuel canister in the first place and anything else should gunpoweder/redstone/glowstone. In the right ratio you get the same amount of items 4-10 times more fuel out. And 40k Fuel per canister holds a long time. Since the refuling is a lot you last a long time with 16 tin. (64 cells). (40k fuel * 21 = 840.000 fuel ticks / 20 = 42k seconds which is 11 hours of constant running in a furnace. 4 times less in a generator.)
And since the FuelCanister give out fuel in 500Tick bursts you dont waste to much energy in the long run. Especially if you calculate that in.

**Comment by Speiger** [comment] 2017-10-17 16:28
Closing just because

**Closed by Speiger** 2017-10-17 16:28 UTC
