### ISSUE TITLE
[Feature Request]Сonfiguration the ability to disable the complete breakdown of nano armor and nano saber quantum armor if the armor is completely discharged.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#790] opened 2023-06-01 12:59 UTC
Please add to the configuration the ability to disable the complete breakdown of nano armor and nano saber quantum armor if the armor is completely discharged.

This is very necessary for many servers, please! Have mercy, do it, it is very necessary, please! The PVP mode is trying very hard with this, the players lose the point of fighting, since the armor does not drop out in the end, the resources that were obtained for the armor = just disappear, help out, help.

Sorry to repeat this topic, but this is very necessary! I hope for your support, thank you!

**Comment by Speiger** [comment] 2023-06-01 14:23
Not interested in doing that change at the moment.
Closing.

**Closed by Speiger** 2023-06-01 14:23 UTC

**Comment by MrJorman** [comment] 2023-06-01 14:55
(((((((((((((((((((((((((((((((((((((((((

**Comment by MrJorman** [comment] 2023-06-04 15:13
Please add. Really need. Soory.

**Comment by Speiger** [comment] 2023-06-04 15:44
@MrJorman you don't accept a No do you?
Last warning.

**Comment by MrJorman** [comment] 2023-06-04 15:45
I seem to be helping you and suggesting and pointing out a lot of bugs, but you block, for what?

**Comment by Speiger** [comment] 2023-06-04 15:49
@MrJorman I have the last say if I want a feature to be added or no.
And i said: NO to changing how quantum armor can be destroyed or not.
Its not a bug its a intentionally implemented feature.

And i told you multiple times that i am not changing my mind on it.

But you don't accept a NO.
And you keep asking, after you were send to timeout, blocked personally and being at your last warning on being banned entirely on discord and github.

**Comment by MrJorman** [comment] 2023-06-04 16:11
Sorry friend, can you tell me where in the code I can set the attack speed of the nano saber? This is perhaps the last thing I would like to ask you.
