### ISSUE TITLE
Copper Cables disconnect on login to server

### ISSUE THREAD

**Issue by Artillect** [TinyModularThings/IC2Classic#214] opened 2016-10-29 04:26 UTC
Whenever I connect to my server, all of the cables in our base are disconnected. Relogging reconnects them.

**Comment by Speiger** [comment] 2016-10-29 06:45
@Artillect which ic2c version do you use?

**Comment by transcondriver** [comment] 2016-10-29 09:47
I remember this issue from an old version. Take a look at issue #150. Have you updated IC2C to ver. 1.2.1.2.4?

**Comment by Speiger** [comment] 2016-10-30 06:24
I assume here that you have a outdated version and did not update @Artillect since you didnt answer in 24h to more define the thing i decided to say "Not a bug in the latest"

**Comment by Artillect** [comment] 2016-10-31 02:17
I'm sorry that I didn't respond. I was using 2.6.69 and have since updated to the newest version. It does not seem to be a problem anymore.

**Comment by transcondriver** [comment] 2016-10-31 02:26
Ah! That version corresponds to the IC2-Experimental versions. This Github Repository is for IC2-Classic. For Experimental, you will either need to visit their bug tracker site at http://bt.industrial-craft.net/my_view_page.php OR visit the main Industrial Craft Forums at http://forum.industrial-craft.net/ .

In any case, glad you managed to resolve your issue. Happy drilling!

**Comment by Artillect** [comment] 2016-10-31 02:49
Shoot, I should have realized that! I'll go submit my issue

**Comment by Speiger** [comment] 2016-10-31 07:49
Hahaha xD Also that should be fixed in later version @Artillect i am closing it.

**Closed by Speiger** 2016-10-31 07:49 UTC
Labels: invalid
