### ISSUE TITLE
[1.19.2] Electric Fishers multiblock preview in the guidebook is invisible

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#516] opened 2022-11-11 18:26 UTC
### Issue
The multiblock preview for the electric fisher doesn't show, probably because the rendering doesn't work for chain blocks

![kuva](https://user-images.githubusercontent.com/77460466/201403844-764cff78-723e-4d74-818f-4cde8750efcb.png)

### Bonus Issue
Also PS, the lighting on the preview is determined by the time of day

![kuva](https://user-images.githubusercontent.com/77460466/201404220-9aa3dce0-0ccf-46e4-971e-377ff20f301b.png)
Night

![kuva](https://user-images.githubusercontent.com/77460466/201404249-adcd01b1-033d-4ca8-b338-f5ad43a17ff7.png)
Morning

![kuva](https://user-images.githubusercontent.com/77460466/201404471-1a4d914c-9ba3-4d37-afde-06b0e5247a5f.png)
Day

### Mod Versions
IC2C: 2.0.1
Forge: 43.1.47

**Comment by Speiger** [comment] 2022-11-11 18:28
Would like to know if a performance mod is installed?
If yes, which one?
And if it happens without a performance mod.

Even if it only happens with the performance mod Ill look into it, just need to know.

**Comment by Vapaman** [comment] 2022-11-15 17:34
I'm using this with Rubidium, but found that it also happens without it happens without it

Without Rubidium:
![kuva](https://user-images.githubusercontent.com/77460466/201987399-3958e85b-1f69-423a-9ebe-6fdaf602a798.png)
![kuva](https://user-images.githubusercontent.com/77460466/201987442-ea0c4da5-ce18-4248-9a7e-eb866f10931d.png)
![kuva](https://user-images.githubusercontent.com/77460466/201987563-152ab73a-cdb4-4ac6-aa21-52fd0165ae7f.png)

**Comment by Speiger** [comment] 2022-11-15 19:32
Ok... Whats your screen resolution?

**Comment by Speiger** [comment] 2022-11-16 18:59
Ok i can reproduce it indev.
Should be fixed this or next patch...

Dunno if i can do it in a short time...

**Comment by Speiger** [comment] 2022-11-16 19:12
Oh yeah... Ok the Electric Fisher offset is wrong thats the reason why... OOps xD will be fixed next patch.

**Closed** 2022-11-21 15:05 UTC
Labels: Fixed
