### ISSUE TITLE
Three bugs

### ISSUE THREAD

**Issue by cubicbyte** [TinyModularThings/IC2Classic#555] opened 2023-01-03 13:56 UTC
Found 3 bugs on version 1.19.2

1. It is possible to fly on a jetpack while you are riding entity, and it's hilarious XD
![2023-01-01_22 03 56](https://user-images.githubusercontent.com/81159301/210368976-c43247fe-34a7-41df-ac3e-5c9a3ed44794.png)
2. https://youtu.be/napzVEem3ok
    How to reproduce:
    1. Inside any machine, press one of these buttons
    2. Click on the JEI input field
    3. Close the menu you opened earlier
3. Curios is needed. If you put the Jetpack in the curios slot, there is a chance to turn it on without a corresponding message. tbh I still don't understand what depends on the chance of this, sometimes it works immediately, sometimes it takes 10 minutes to click. However, after that you can fly without wasting a charge

**Comment by Speiger** [comment] 2023-01-03 14:01
Ty for the report.

1: Not a bug. We actually add code specifically to make that work.
2: have to test that.
3: could it be that you have a battery in your inventory? Because jetpacks also drain charge from other energy providers in your armor/curio slots.

**Comment by cubicbyte** [comment] 2023-01-03 14:20
@Speiger, About 3rd: No, a completely empty inventory. When this happens and you go into the Curios menu, it turns off and you have to repeat it. Also, I seem to have found the best way to reproduce this bug: Put on the Jetpack on the Back slot and turn it on. Then click the switch button 3 times at a certain speed, chance of success is great. By the way, if you do this, the flight on Entity will be at an increased speed, without "freezes".

**Comment by Speiger** [comment] 2023-01-11 04:05
@cubicbyte ok 2 isn't really fixable. I implemented a patch where the chance of it staying forever is dealt with but basically a gui supports that when you press "Tab" will cycle through all buttons and this feature basically makes the bug that text stays.
Basically buttons can be focused and or hovered. Either of these show the tooltip.

This bug is basically happening where it breaks the "Focused" state.
Which I can not really fix. So my fix is to disable the focus after a click.

This won't fix it fully but at least makes it away when you click on it without having to close the gui or having to press tab all the time.

**Comment by Speiger** [comment] 2023-01-11 04:21
Also Last bug (the jetpack one) I will not fix because having to do something for 5 minutes to get 1 chance.
isn't feasable testeable.
So i did at least something.

**Closed** 2023-01-17 20:13 UTC
Labels: Fixed
