### ISSUE TITLE
Connecting a LV transformer directly to an MFE fails randomly 

### ISSUE THREAD

**Issue by Maoman1** [TinyModularThings/IC2Classic#484] opened 2022-10-29 06:54 UTC
By "directly" I mean putting the transformer directly adjacent to the MFE and using the wrench to turn the transformer's input side toward the MFE, avoiding the need for gold cable entirely. 

Doing this will work... for a while. Then, after a random (as far as I can tell) amount of time somewhere in the range of half an hour it will suddenly stop transferring EU packets from the MFE to the Transformer. "Resetting" the transformer's rotation, i.e. turning it away from the MFE, then rotating it back toward the MFE, causes it to start working again.

Moving the Transformer one block away and using a gold cable stops the issue, it's only when they are directly adjacent.

**Comment by Speiger** [comment] 2022-10-29 07:28
@Maoman1 was there a redstone signal nearby?
If yes then you set the Transformer to "Upvolt" which causes a transformer only to accept LOW power on the output, and output high on the "input"

**Comment by Maoman1** [comment] 2022-10-29 19:21
No. There was a batbox I had set to emit if more than half full, but it was diagonal from the transformer, not directly adjacent.

**Comment by Speiger** [comment] 2022-10-29 20:14
@Maoman1 that was it. Redstone signals travel 2 blocks far. Direct Connection and Indirect connection.

Not a bug. You just didn't know about vanilla mechanics.

**Comment by Maoman1** [comment] 2022-10-29 22:49
Place a piston in the exact same place as the transformer and it does not extend. But thanks for the condescending attitude, really appreciate that.

**Comment by Maoman1** [comment] 2022-10-29 22:55
[In this image](https://i.imgur.com/bIroEeW.png) you can clearly see the batboxes are both emitting a signal and the MFEs are not. The piston and the LV Transformer are in the same respective place. Therefore the transformer is **not** receiving a signal.

**Comment by Speiger** [comment] 2022-10-30 00:07
> Place a piston in the exact same place as the transformer and it does not extend. But thanks for the condescending attitude, really appreciate that.

Ok, I am sorry that this comment was received as condescending. It wasn't meant that way.
I answered to with how I understood the setup. Meaning, I wasn't understanding it how you meant it.

> [In this image](https://i.imgur.com/bIroEeW.png) you can clearly see the batboxes are both emitting a signal and the MFEs are not. The piston and the LV Transformer are in the same respective place. Therefore the transformer is not receiving a signal.

This is now something i can work with.
Is this reproduce able?

Could you make a clip reproducing it?
So I can see exactly what happened?

This would help address this issue ASAP.

**Comment by Maoman1** [comment] 2022-10-30 13:22
It was the "You just didn't know about vanilla mechanics" that came across as condescending. I understand you didn't mean it that way and appreciate the apology.

I cannot video it because like I said in the original post it would happen seemingly randomly after a significant amount of time has passed, roughly 15-30 minutes. I doubt it's literally based on the time passing, rather there is some rare condition that triggers it, but I was not able to figure out what caused it. The only "clue" I could discern was that rotating the transformer away from the MFE and then back toward it again would cause it to start working again.

**Comment by Speiger** [comment] 2022-10-30 16:12
> The only "clue" I could discern was that rotating the transformer away from the MFE and then back toward it again would cause it to start working again.

if the transformer starts not working when it is attached to a MFE, means it gets powered by redstone.
Which inverts it, which is why the explosion happened.

Now the one thing I can  think of is that ic2c is doing some redstone detection weird.
But before you start screaming, mc has 0 good way of detecting redstone. There is at least 5 different ways with ups and downs.

And it could be the way i am using detects the redstone torch while the piston has a different redstone check that doesn't detect it.

Anyways a good way to find out if it would explode is to check if the transformer isn't emitting power even so there is power to receive and to emit.

**Comment by Maoman1** [comment] 2022-10-30 16:47
>if the transformer starts not working when it is attached to a MFE, means it gets powered by redstone.
Which inverts it, which is why the explosion happened.

Well first off nothing ever exploded on me. Not sure where you got that from. Maybe just an assumption that transformer issues tend to result in explosions? It didn't this time.

But I think you might be misunderstanding what I'm trying to describe here: The transformer was attached to the MFE with the 3 dot side facing it, then after some time power stopped flowing for no apparent reason. Then I used the wrench to rotate the 3 dots to a different direction, then immediately rotated it back toward the MFE again without changing anything else, and power flowed again. This happened multiple times, this exact sequence.

**Comment by Speiger** [comment] 2022-10-30 16:52
> Well first off nothing ever exploded on me. Not sure where you got that from. Maybe just an assumption that transformer issues tend to result in explosions? It didn't this time.

When inverted the input becomes the output and the output becomes the input.
Since the output is expected to be Low voltage it makes sense that it won't explode then.
But if you rotate the "output" to touch the MFE output while the transformer is inverted, ofc then it explodes.

In laymen term's: You invert the flow direction.

**Comment by Maoman1** [comment] 2022-10-30 16:55
When I rotated the transformer, the low voltage input side was directly touching the MFE's output. The blocks were directly adjacent. It did not explode. 

If it _should_ have exploded, then that's just more evidence that something had stopped the flow of power. Maybe the MFE had stopped outputting for some reason, but "reconnecting" the HV side woke it up again. I dunno.

**Comment by Speiger** [comment] 2022-10-30 17:03
No It should only explode if power is transferred, not if the "possibility" of power is transfer is there.

Meaning the transformer was already full, causing it not to explode.

**Closed** 2022-10-31 01:12 UTC
