### ISSUE TITLE
crash server.

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#822] opened 2023-06-21 13:51 UTC
[crash-2023-06-21_16.47.26-server.txt](https://github.com/TinyModularThings/IC2Classic/files/11818288/crash-2023-06-21_16.47.26-server.txt)

The player reported that he combined 2 wires before the server crashed

**Comment by Speiger** [comment] 2023-06-21 14:38
@GitJhopa there is a temp fix that disables the crash but causes energy to randomly not flow because of said crash in the configs.

I would love to fix this bug, the issue is that it requires a reproduce able setup that i can easily test with.
If you could provide me one that would be lovely.

If you just want to use the config and not help fix this bug just close this issue.

Small side note:
The config won't exist forever.

**Closed** 2023-07-12 21:09 UTC
