### ISSUE TITLE
Reactor Tracking Upgrade extracting Coolant Cells doesn't work.

### ISSUE THREAD

**Issue by Erik3003** [TinyModularThings/IC2Classic#428] opened 2020-09-10 17:44 UTC
The Reactor Tracking Upgrade generally works, inserting Coolant Cells or inserting and extracting other components works without issues, but extracting Coolant Cells (and maybe things that extract on the same logic) doesn't work, it doesn't extract even when all that remains is one point of durability.

**Comment by Speiger** [comment] 2020-10-10 05:29
@Erik3003 only rechargeable components are extract able as we discussed. So closing this since its intended behavior

**Closed by Speiger** 2020-10-10 05:29 UTC
