### ISSUE TITLE
Rocket miner allows start of work without mining pipes

### ISSUE THREAD

**Issue by Chikko5** [TinyModularThings/IC2Classic#939] opened 2024-01-05 16:08 UTC
If you put scanner into rocket miner which is not supplied with mining pipes, it will immediately start flying around up and down until battery charge reaches zero.

IC2 1.19.2-2.0.8.1

**Comment by Speiger** [comment] 2024-01-05 16:12
That is technically not a bug...

**Comment by Chikko5** [comment] 2024-01-05 16:20
Well yes, but it would be nice to have a feature of not allowing rocket miner to start without pipes. Or at least mention this thing in ingame wiki to prevent unpleasant situations. Imagine if you put fully charged glowtronic crystal, forget about pipes, put scanner and then wait an eternity until the crystal discharges and the miner flies to refueling position.

**Comment by Speiger** [comment] 2024-01-05 23:25
Yeah that is the reason why i didn't close the issue.

**Closed** 2024-02-26 07:58 UTC
Labels: Fixed
